### ISSUE TITLE
Suggestions `#![no_std]` Use `core` and `alloc` rather than `std`

### ISSUE THREAD

**Issue by ten3roberts** [azriel91/tynm#13]
This would greatly help for no std environment or for ensuring that this crate does not perform IO, which is useful for wasm support.

I think this would be accomplished by adding `#![no_std]` and switching imports and importing things such as `String` and `Vec` which are no longer the prelude.

I have used this crate inside [flax](https://github.com/ten3roberts/flax) to greatly reduce error message noise due to heavy use of generics in Queries. Unfortunately I had to temporarily remove `tynm` in order to support `no_std`, but it would be great to see this crate back.

Thank you.

**Comment by azriel91** [comment]
Heya :wave:, I've tried implementing this in #14, could you check if this works in `flax`?

```toml
# probably need to also change this in [dependencies]
# because the crate version in the branch is 0.1.8
tynm = "0.1.8"

[patch.crates-io]
tynm = { git = "https://github.com/azriel91/tynm.git", branch = "feature/13/support-no-std" }
```
